### PR TITLE
QuickShulker support

### PR DESCRIPTION
**Pull request by kyrptonaught**
Adds QuickShulker support for ShulkerLootCrates.

### CODE REVIEW

**Comment by kyrptonaught** [comment]
This dose not include QuickShulker by default, players will still be able to use the mod without QuickShulker installed. QuickShulker will respect if the shulker is locked or not before opening and will display your message if it is. Feel free to make any changes!

**Comment by kyrptonaught** [comment]
Wait this is bork, let me fix

**Comment by kyrptonaught** [comment]
Think it's good now.

**Comment by kyrptonaught** [comment]
Just an FYI, this will require Quickshulker 1.2.1, which I have not released yet. But I hope to later tonight.

**Comment by DaFuqs** [comment]
Ty for adding support! I appreciate it.
I added additional support for opening chest crates via QuickShulker, if the config setting is set that chest crates should keep their inventory on break. (0b9e80472d2f74705d0252fce9c0dde010ab5d88)

What I noticed when testing it out is that LootableContainerBlockEntitys checkLootInteraction() does not run when opening the items inventory via QuickShulker (so the player has to place and open the box for new items to generate).

That would be true for vanilla shulkers, too, if an item and the placed LootableContainerBlockEntity has the tag "LootTable" set.
Since that function only exists in containers BlockEntities and not in the items adding this special case may be a bit more complicated, though...

Since I saw your comment in the second commit message: Would opening a shulker with the "LootTable" tag set may remove that tag, too? I will be able to test it tomorrow, but in the meantime, maybe you already know the answer.

**Comment by kyrptonaught** [comment]
Hm yeah most likely that data will get wiped if there aren't any items in the shulker. I can implement a smarter check. This would remove the need for your custom ItemStackInventory. 

I can experiment with checkLootInteraction. It looks like theoretically it is possible. I haven't received any complaints of users wanting the checkLootInteraction. But I suppose it is important for this mod

**Pull request merged**
